[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "sqlite.dev"]
variables = { PYTHON_VERSION = "3.11" }

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"

